# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-23 07:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0003_document_upfile_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='EdlRecord',
            fields=[
                ('result_file', models.CharField(max_length=128, primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='document',
            name='id',
        ),
        migrations.AlterField(
            model_name='document',
            name='upfile_hash',
            field=models.CharField(default=b'd41d8cd98f00b204e9800998ecf8427e', max_length=256, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='edlrecord',
            name='original_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.Document'),
        ),
    ]
