# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-29 10:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0004_auto_20160423_0759'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='up_file',
        ),
        migrations.AddField(
            model_name='document',
            name='process_time',
            field=models.FloatField(default=0.0),
        ),
    ]
