# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-29 10:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0005_auto_20160429_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='upfile_name',
            field=models.CharField(default='', max_length=256),
        ),
    ]
