# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-29 11:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0007_document_upload_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='upload_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
